name: Go
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Fetch all tags
        run: git fetch --depth=1 origin '+refs/tags/*:refs/tags/*'
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: pip install --requirement requirements.package.txt
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('README.md') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Generate library
        run: make build-go
      - name: Configure Git
        run: |
          git config --global user.email bryan.mckelvey@gmail.com
          git config --global user.name 'Bryan McKelvey'
      - name: Deploy library
        if: github.ref == 'refs/heads/master'
        run: make deploy-go GITHUB_TOKEN=${{ secrets.REPO_TOKEN }}
