name: go
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - name: Fetch all tags
        run: git fetch --depth=1 origin '+refs/tags/*:refs/tags/*'
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: pip install --requirement requirements.package.txt
      - name: Print versions
        run: make version
      - name: Generate and build Go libraries
        run: make build-go
      - name: Deploy Go libraries
        if: github.ref == 'refs/heads/master'
        run: make deploy-go
