name: Java
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      OSSRH_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
      OSSRH_GPG_KEYNAME: ${{ secrets.OSSRH_GPG_KEYNAME }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Fetch all tags
        run: git fetch --depth=1 origin '+refs/tags/*:refs/tags/*'
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: pip install --requirement requirements.package.txt
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up ~/.m2/settings.xml
        run: cp config/settings.xml ~/.m2/settings.xml
      - name: Import GPG key
        run: echo "${{ secrets.OSSRH_GPG_KEY }}" | base64 --decode | gpg --import --no-tty --batch --yes
      - name: Generate and build artifacts
        run: make build-java
      - name: Deploy artifacts
        if: github.ref == 'refs/heads/master'
        run: make deploy-java
