name: Java
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Fetch all tags
        run: git fetch --depth=1 origin '+refs/tags/*:refs/tags/*'
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: pip install --requirement requirements.package.txt
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate and build artifacts
        run: make build-java
      - name: Deploy artifacts
        if: github.ref == 'refs/heads/master'
        run: make deploy-java
